name: linux-flavors

services:
  alpine:
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk update && apk upgrade
        RUN apk add --no-cache bash curl htop git openssh rsync tmux wget zsh
    command: bash

  arch:
    build:
      dockerfile_inline: |
        FROM archlinux:latest
        RUN yes | pacman -Sy bash curl htop git openssh rsync tmux wget zsh
        RUN yes | pacman -Sy nix
    command: zsh

  kali:
    build:
      dockerfile_inline: |
        FROM kalilinux/kali-rolling:latest
        # RUN apt update && apt -y install kali-linux-headless
    command: bash

  nix:
    build:
      dockerfile_inline: |
        FROM nixos/nix:latest
    command: bash
